const seedAds = [
  {
    title: "iPhone 15 Pro Max - 256GB, Natural Titanium",
    category: "electronics",
    price: 320000,
    location: "DHA, Lahore",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&q=80",
    featured: 1,
    verified: 1,
    posted_at: "2h ago",
    views: 1240,
    seller_name: "Ali Raza",
    seller_rating: 4.9,
    seller_deals: 47,
    condition: "Like New",
    description: "Genuine sealed box, complete accessories. 10/10 condition. Serious buyers only.",
  },
  {
    title: "Toyota Corolla 2022 - X Grade, 1.6 Automatic",
    category: "vehicles",
    price: 5800000,
    location: "Gulberg, Lahore",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&q=80",
    featured: 1,
    verified: 1,
    posted_at: "5h ago",
    views: 3450,
    seller_name: "Usman Cars",
    seller_rating: 4.7,
    seller_deals: 122,
    condition: "Excellent",
    description: "First owner, all original, never driven outside Lahore. Full service history.",
  },
  {
    title: "MacBook Pro M3 - 14 inch Retina, Space Gray",
    category: "electronics",
    price: 450000,
    location: "Model Town, Lahore",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80",
    featured: 0,
    verified: 1,
    posted_at: "1d ago",
    views: 890,
    seller_name: "Tech Hub PK",
    seller_rating: 4.8,
    seller_deals: 89,
    condition: "New",
    description: "Fresh import, Apple warranty. Full box accessories. Invoice provided.",
  },
  {
    title: "5 Marla House for Sale - Bahria Town Phase 8",
    category: "property",
    price: 14500000,
    location: "Bahria Town, Rawalpindi",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=80",
    featured: 1,
    verified: 0,
    posted_at: "3d ago",
    views: 5600,
    seller_name: "Naveed Property",
    seller_rating: 4.5,
    seller_deals: 34,
    condition: "N/A",
    description: "Corner plot, 3 bedrooms, 2 bathrooms, American kitchen. Ready for possession.",
  },
  {
    title: "Sony PlayStation 5 - Disc Edition",
    category: "electronics",
    price: 115000,
    location: "Johar Town, Lahore",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&q=80",
    featured: 0,
    verified: 1,
    posted_at: "12h ago",
    views: 2100,
    seller_name: "Gaming Zone",
    seller_rating: 4.6,
    seller_deals: 63,
    condition: "Good",
    description: "2 controllers, 3 games included. Minor scratches on box only.",
  },
];

module.exports = { seedAds };
